name: eapo_mobile_app
description: EAPO-mobile application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.10
  # Add the dependency for the Firebase Core Flutter SDK
  firebase_core: ^1.10.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^8.3.4

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_messaging: ^11.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Work with web
  url_launcher: ^6.0.9
  flutter_inappwebview: ^5.3.2

  # Converter cp1251
  windows1251: ^0.0.3
  enough_convert: ^1.4.0

  # SVG support
  flutter_svg : ^0.22.0

  # Network provider
  http: ^0.13.4

  # Xml, json parsers
  json_annotation: ^4.3.0
  xml: ^5.3.1
  xml2json: ^5.3.1

  # Work with files
  path_provider: ^2.0.7

  # Plugin shared preferences
  shared_preferences: ^2.0.8

  # BLoC dependency
  flutter_bloc: ^7.3.3

  # open pdf files
  flutter_pdfview: ^1.2.1

  # adds permissions to download files
  permission_handler: ^8.3.0

  flutter_app_badger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # For generate .g.dart files
  # just run in terminal "flutter pub run build_runner build"
  build_runner: ^2.1.4

  # json serializer
  json_serializable: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo_main.svg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: MyFlutterApp
      fonts:
        - asset: assets/MyFlutterApp.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
